#!/bin/sh
BASEDIR=$(dirname $0)
cd $BASEDIR
cd ..

# Build the dissertation.
xelatex -interaction=nonstopmode dissertation
bibtex -interaction=nonstopmode dissertation
xelatex-interaction=nonstopmode  dissertation
xelatex -interaction=nonstopmode dissertation

# Hide the log.
mv "dissertation.log" ".logged"

