#! /bin/bash

COMMAND="pdflatex -halt-on-error -interaction=nonstopmode --interaction=batchmode --shell-escape thesis.tex && \
    echo '--------------------------------------------------' &&\
    bibtex thesis && \
    echo '--------------------------------------------------' &&\
    pdflatex -halt-on-error -interaction=nonstopmode --interaction=batchmode --shell-escape thesis.tex %%
    echo '' &&\
    echo '==================================================' &&\
    echo ''"
 
eval "$COMMAND"
