#! /bin/bash

COMMAND="pdflatex -halt-on-error -interaction=nonstopmode thesis.tex && \
    bibtex thesis && \
    pdflatex -halt-on-error -interaction=nonstopmode thesis.tex && \
    ./scripts/status > word-count.md"

find . -regex ".*\.\(cls\|tex\|bib\)" \
    | entr bash -c "$COMMAND"
