#! /bin/bash

COMMAND="pdflatex -halt-on-error -interaction=nonstopmode --shell-escape thesis.tex && \
    bibtex thesis && \
    makeindex thesis && \
    pdflatex -halt-on-error -interaction=nonstopmode --shell-escape thesis.tex"
  
find . -type f \( -name "*.cls" -o -name "*.tex" -o -name "*.bib" -o -name "*.png" \) \
    | entr bash -c "$COMMAND"
