#! /bin/bash

COMMAND="pdflatex -halt-on-error -interaction=nonstopmode --interaction=batchmode --shell-escape thesis.tex && \
    echo '--------------------------------------------------' &&\
    bibtex thesis && \
    echo '--------------------------------------------------' &&\
    pdflatex -halt-on-error -interaction=nonstopmode --interaction=batchmode --shell-escape thesis.tex %%
    echo '' &&\
    echo '==================================================' &&\
    echo ''"

find . -path './data' -prune -o -path './.git' -prune -o -print \
    | grep '\.tex$\|\.cls$\|\.bib$' \
    | entr bash -c "$COMMAND"
