#! /bin/bash

COMMAND="pdflatex -halt-on-error -interaction=nonstopmode thesis.tex && \
    bibtex thesis && \
    makeindex thesis && \
    pdflatex -halt-on-error -interaction=nonstopmode thesis.tex && \
    ./scripts/status > word-count.md"

find . -path ./data -prune -o -print -regex ".*\.\(cls\|tex\|bib\)" \
    | entr bash -c "$COMMAND"
